Expand Submitter to HTCondor
LEAF-HQ/LEAF pull request #49
Opened 2022-01-08 18:34 UTC by anmalara

Addressing #42.

-[x] Created TimeFormat class. It stores the days, hours, minutes, seconds and performs comparisons.
-[x] Created  ClusterSpecificSettings. It's a class that stores information related to each supported Cluster. It also provides a method to get the closest upper limit for the time allowed by the Cluster (given an input time).
-[X] simplified utils func. 
-[x] Create CondorBase class. Uses python bindings of htcondor, creates and stores the Job Info, submits a single job or a list of jobs to the clusters, allow interactions with the Cluster.
-[x] Exented Submitter and submit.py to support HTCondor
-[x] Tested
- [ ] Clean the code
- [ ] Expand with further functionalities
- [] Generalise

DO NOT MERGE YET, but provide feedback.
[ci skip]

2022-01-08 19:49 UTC, reimersa requested changes

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        self.time = {'g':0,'h':0,'m':0,'s':0}
what does `'g'` stand for? Giorno?

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        if "lxplus" in name.lower():
please use `'` as string delimiters, not `"`

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        self.Settings["Cluster"] = "slurm"
`'` vs `"`

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        self.Settings["Cluster"] = "htcondor"
`'` vs `"`

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        return self.Settings()
This function only works for lxplus, but not for slurm@psi yet, even though some settings exist already. Why is that?

2022-01-08 19:49 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        raise ValueError(red('Runtime exceeds 7 days, please choose something a bit faster.'))
What is the purpose of this function? It has inconsistent return types, is this intended?

2022-01-08 19:49 UTC, reimersa commented on Submitter/CondorBase.py
> +
why is this repeated? This is defined in `Generator/utils.py`

2022-01-08 19:49 UTC, reimersa commented on Submitter/CondorBase.py
> +def prettydic(d, indent=8, color=blue):
please rename to `prettydict`

2022-01-08 19:49 UTC, reimersa commented on Submitter/Submitter.py
> +            if cluster.upper() == "SLURM":
`'` vs `"`

2022-01-08 19:49 UTC, reimersa commented on Submitter/submit.py
> +    parser.add_argument('--cluster', '-k', action='store', type=str, default="htcondor", dest='cluster', help='Submit split jobs to cluster. Default is SLURM')
maybe `-b`, `--batch`?

2022-01-08 19:56 UTC, anmalara commented on Generator/ClusterSpecificSettings.py
> +        if "lxplus" in name.lower():
done

2022-01-08 19:57 UTC, anmalara commented on Generator/ClusterSpecificSettings.py
> +        return self.Settings()
Not complete yet. Will fix it.

2022-01-08 19:58 UTC, anmalara commented on Submitter/CondorBase.py
> +def prettydic(d, indent=8, color=blue):
done

2022-01-08 20:00 UTC, anmalara commented on Submitter/Submitter.py
> +            if cluster.upper() == "SLURM":
done

2022-01-09 12:50 UTC, anmalara commented on Generator/ClusterSpecificSettings.py
> +        return self.Settings()
Done

2022-01-09 12:53 UTC, anmalara commented on Submitter/submit.py
> +    parser.add_argument('--cluster', '-k', action='store', type=str, default="htcondor", dest='cluster', help='Submit split jobs to cluster. Default is SLURM')
Not convinced. HTCondor and slurm are clusters. Batch could be a keyword for something else in the future.

2022-01-09 16:07 UTC, anmalara commented on Generator/ClusterSpecificSettings.py
> +        raise ValueError(red('Runtime exceeds 7 days, please choose something a bit faster.'))
Changed. Let's think over this

2022-01-09 17:51 UTC, reimersa requested changes

2022-01-09 17:51 UTC, reimersa commented on Submitter/UserSpecificSettings.py
> +        return self.UserInfo[name]
it's actually using json, not xml

2022-01-09 17:51 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +            self.Settings['MaxRunTime'] = ('','00:00:00')
use `None` as default

2022-01-09 17:51 UTC, reimersa commented on Generator/ClusterSpecificSettings.py
> +        self.Settings['queue']['long'] = TimeFormat('24:00:00')
Here and below: take name of key from first line

2022-01-09 17:51 UTC, reimersa commented on Submitter/UserSpecificSettings.py
> +            'xml':      self.GetXMLPath(name),
info is redundant

2022-01-09 17:51 UTC, reimersa commented on Submitter/Settings_anmalara.xml
> +}
remove specific file

2022-01-09 17:51 UTC, reimersa commented on Submitter/Settings_exampleuser.xml
> +    "xml": "SUBMITTERPATH/Settings_username.xml"
remove `xml` field

2022-01-09 17:51 UTC, reimersa commented on Submitter/submit.py
> +    parser.add_argument('--cluster', '-k', action='store', type=str, dest='cluster', default='', help='Submit split jobs to cluster. Default is taken from UserSpecificSettings')
copy-paste description error

2022-01-09 17:51 UTC, reimersa commented on Submitter/CondorBase.py
> +            self.ModifyJobInfo(self.RequestTime,self.Time)          # Time requested
rename `RequestTime` to a more descriptive name, like `RequestTimeSettingName` or similar

2022-01-10 09:20 UTC, anmalara commented on Submitter/UserSpecificSettings.py
> +        return self.UserInfo[name]
Done

2022-01-10 09:22 UTC, anmalara commented on Generator/ClusterSpecificSettings.py
> +            self.Settings['MaxRunTime'] = ('','00:00:00')
Done

2022-01-10 09:22 UTC, anmalara commented on Submitter/UserSpecificSettings.py
> +            'xml':      self.GetXMLPath(name),
done

2022-01-10 09:24 UTC, anmalara commented on Submitter/Settings_anmalara.xml
> +}
Done

2022-01-10 09:24 UTC, anmalara commented on Submitter/Settings_exampleuser.xml
> +    "xml": "SUBMITTERPATH/Settings_username.xml"
Done

2022-01-10 09:24 UTC, anmalara commented on Submitter/Settings_exampleuser.xml
> +    "xml": "SUBMITTERPATH/Settings_username.xml"
Done

2022-01-10 09:25 UTC, anmalara commented on Submitter/CondorBase.py
> +            self.ModifyJobInfo(self.RequestTime,self.Time)          # Time requested
Done

2022-01-10 09:28 UTC, anmalara commented on Submitter/submit.py
> +    parser.add_argument('--cluster', '-k', action='store', type=str, dest='cluster', default='', help='Submit split jobs to cluster. Default is taken from UserSpecificSettings')
Done

2022-01-10 09:48 UTC, anmalara commented on Submitter/submit.py
> +    parser.add_argument('--cluster', '-k', action='store', type=str, dest='cluster', default='', help='Submit split jobs to cluster. Default is taken from UserSpecificSettings')
Done

2022-01-10 11:11 UTC, reimersa approved these changes

2022-01-10 11:12 UTC, merged